### ISSUE TITLE
Dash board - system notice text

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#1]
Hello Galen

Please see below new text

Hello Anthony Aoun,
Welcome to Property Compass version 2!
For New Users: Property Compass is a platform designed to enable collaboration and business opportunities within the 'Real Estate' sector.

For Existing Users: This platform is a complete rewrite from the ground up and represents a significant investment in new technology that will be the foundation for all new features as well as the powerful tools you are familiar with from the previous version.
Galen Parker 
Chief Technology Officer

Change text to: 

Hello <user>

Welcome to PropertyCompass® release 2.0

For New Users: PropertyCompass® provides independent industry reports and a marketplace, enabling real-time collaboration between buyers, sellers and industry professionals within the Real Estate industry.

For Existing Users: The PropertyCompass® application is being rebuilt module by module; this is a complete rewrite from the ground up and represents a significant investment in new technology that will be the foundation for all new features as well as the powerful tools you are familiar with.

Galen Parker 
Chief Technology Officer

AA

**Comment by galenp** [comment]
I think the 'release 2.0' part can be completely removed... we dont need to show that detail to B2C customers yeah?

**Comment by galenp** [comment]
Fixed in dc8790cce6455bda2febcc34f2e4d9086648d0b1

**Comment by anthonyaoun** [comment]
you should NOT close an issue; the issuer closes the issue to ensure it is done.

AA

**Comment by anthonyaoun** [comment]
corrections needed

AA

![issue-01](https://cloud.githubusercontent.com/assets/7224727/7386319/b76a3142-ee95-11e4-9550-d60b3f8bf796.png)

**Comment by anthonyaoun** [comment]
Thank you
