### ISSUE TITLE
ListingAListing

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#100]
Please see attached

AA

![selectingalisting](https://cloud.githubusercontent.com/assets/7224727/14425400/5beaca32-002a-11e6-9718-54478130c4e2.png)

**Comment by galenp** [comment]
When you select a listing the TAG for that listing appears in the select area and the listing is removed from the list of available listings.

E.g.
http://angular-ui.github.io/ui-select/demo-multiple-selection.html

I'm not 100% happy with this interface... but there is a fair amount of new coding to be done to make a regular dropdown list automatically remove already selected items. I'll get around to it but for now this method is easier.

**Comment by galenp** [comment]
Also, with regard to the drop down list.. I just tested and when i select from the DROP DOWN the list remains open.

**Comment by galenp** [comment]
This UI was considerably revamped since this issue was raised, closing.
