### ISSUE TITLE
Report Footer and header

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#104]
Please see attached

AA

![report-footer-header](https://cloud.githubusercontent.com/assets/7224727/14439078/a6a425a4-006c-11e6-89d5-e2fef0601bc5.png)

**Comment by galenp** [comment]
The lister doesn't have the details stored so they were not transcribed onto the report.

A complete user profile does get put in that location.

I'll review the footer... I'm not comfortable with "PropertyCompass.Com.Au" ever being used.

We have a Registered "Property Compass" so suggest we only use that for our brand.

So maybe "Powered by Property Compass &reg;"

**Comment by galenp** [comment]
Ok updated footer to : Property List powered by Property Compass &reg;

Closing this ticket.
