### ISSUE TITLE
Notice drop box

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#105]
please see attached

AA

![notice-drop-down](https://cloud.githubusercontent.com/assets/7224727/14455391/98f0d8dc-00e2-11e6-93b3-69504c04cbb6.png)

**Comment by galenp** [comment]
Ok so .. in brackets Messages (0), Notices (0), Tasks(0) represent how many of each type you have as in counters.

The number in the blue or red icon is how many unread.

**Comment by galenp** [comment]
Ok changed it so the Tasks (X) number is related to the UNREAD notices for that type.
