### ISSUE TITLE
Menu and Sub-Menus

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#11]
Please see attached

AA

![menu-labels](https://cloud.githubusercontent.com/assets/7224727/7386645/9c282732-ee99-11e4-907d-db9658be69c6.png)

**Comment by anthonyaoun** [comment]
In this slide I mean: That 

Independent Reports (the new name for Reviews) 

get 3 sub-menus. 

Order
Saved
Pending payment

AA

**Comment by galenp** [comment]
I think i need to discuss some of these concepts verbally with you to workshop a solution.

**Comment by galenp** [comment]
Resolved in recent round of commits. Please close.

**Comment by anthonyaoun** [comment]
Thank you
