### ISSUE TITLE
System notice

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#112]
Hi Galen

Please see attached

AA

![system-notice](https://cloud.githubusercontent.com/assets/7224727/14603428/e3cf41d6-05b0-11e6-8c39-02565102e4d1.png)

**Comment by galenp** [comment]
In the screen shot you are on the "Add Listing" screen? Did you intend to be on the Add Property List screen? Even then... you could create a property list for network listings and still not require listings.

Going to close I think its a non issue.
