### ISSUE TITLE
main Screen

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#114]
Hello Galen

please see attached

AA

![propertylist-mainscreen](https://cloud.githubusercontent.com/assets/7224727/14764008/71c3587c-09eb-11e6-8bac-9af272bb9c02.png)

**Comment by galenp** [comment]
There has been some UI improvements from here but I think as of Feb 2017 these features are going to reside more in a new Networks section so ill close this issue pending that roadmap.
