### ISSUE TITLE
Report order and Lot numbers

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#119]
Hi Galen,

Please see attached 

Thank you
AA

![feeback-28thmay-01-aa](https://cloud.githubusercontent.com/assets/7224727/15624203/def63240-24c4-11e6-9566-7860d80b2972.jpg)

**Comment by galenp** [comment]
Unit numbers were added and the last update date is based on the last time the property list was changed not the report print date.
