### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#121]
Hi Galen

Please see attached

AA

![feedback-aa-04jun-06](https://cloud.githubusercontent.com/assets/7224727/15798847/468045ce-2a8b-11e6-86e6-510d6ff4c81e.jpg)

**Comment by anthonyaoun** [comment]
and this one

![feedback-9thjune](https://cloud.githubusercontent.com/assets/7224727/15908727/716210c8-2e06-11e6-91df-121d8b6dc0b6.jpg)

**Comment by galenp** [comment]
Fixed in https://bitbucket.org/propertycompass/pc.component.propertylists/commits/7e3c09111bd2d5c4bdeb4a9e3e929a43bb6d0c3a
