### ISSUE TITLE
Payment details page - Credit Card number - restrict input values

### ISSUE THREAD

**Issue by kajalshah** [galenp/PROPERTYCOMPASS.ISSUES#16]
Please refer attached image

thanks,
![paymentdetails-cardnumber-29april2015](https://cloud.githubusercontent.com/assets/6513000/7390228/6a6bb78c-ee93-11e4-89d8-b236ae103cef.png)

**Comment by galenp** [comment]
dupe of galenp/propertycompass.issues#17 closing.
