### ISSUE TITLE
Order ipr screen Plus submenu

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#2]
Galen

Please see attached image

Thank you
AA

![order-ipr](https://cloud.githubusercontent.com/assets/7224727/7383836/bfb27340-ee69-11e4-9930-0d6f2468469c.png)

**Comment by galenp** [comment]
do you think that by adding these big complicated globs of text into the product selection that the user is bombarded with too much information to read? Could this information be distilled into simpler amounts?

**Comment by galenp** [comment]
I also dont think we need to specify the GST/pricing concerns in product selection.

If a user is on this page they have an account. The problem of whether an invoice has GST or not i think is an invoicing/payments concern. Perhaps we just state the exTax price.

**Comment by anthonyaoun** [comment]
GST and NO GST applicable is a needed function to serve potential overseas users.

we could include this in the confirmation page.
i) save and return to update profile
ii) continue pay with GST

There is a specific section for this in the wire frame. order ipr / step 3> http://gug7sp.axshare.com/ 

Declaration for non-payment of GST

AA

**Comment by galenp** [comment]
![image](https://cloud.githubusercontent.com/assets/1113659/7384162/b83d83ac-ee5f-11e4-8361-0b890808d6ae.png)

Please create a new Github for the Reviews -> My Reviews as this is a development component and is big enough to track and manage in isolation. This would certainly be a ScrumDo task.

**Comment by galenp** [comment]
With regards to GST the discussion is valid and ongoing but separate to this issue. I think a new issue is raised for GST discussion.

**Comment by galenp** [comment]
The actionable fixes for this issue have been committed under commit: 8797a8c8df7ca19f2746aef094cb25f986fb41bf

**Comment by galenp** [comment]
8797a8c8df7ca19f2746aef094cb25f986fb41bf

**Comment by galenp** [comment]
Fixed in 8797a8c8df7ca19f2746aef094cb25f986fb41bf

**Comment by galenp** [comment]
https://github.com/galenp/PROPERTYCOMPASS.APP/commit/8797a8c8df7ca19f2746aef094cb25f986fb41bf

**Comment by anthonyaoun** [comment]
Please link sample button / open in new tab

http://www.propertycompass.com.au/wp-content/uploads/2015/04/sample-ipr.pdf

AA

**Comment by galenp** [comment]
should be resolved now, please test and close

**Comment by anthonyaoun** [comment]
Thank you

AA
