### ISSUE TITLE
2nd Pass - Logout screen 

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#22]
AA
![2ndpass-30th-april-logoutscreen](https://cloud.githubusercontent.com/assets/7224727/7404768/bde813fe-ef2b-11e4-9c25-3ecfba246a84.png)

**Comment by galenp** [comment]
Relabelled as per updates to labelling system... confirmed the issue

**Comment by galenp** [comment]
Resolved.. should be ok to close as the resolution is so very clear.

![image](https://cloud.githubusercontent.com/assets/1113659/7448332/a0ba9628-f249-11e4-9291-c22e571d7111.png)
