### ISSUE TITLE
2nd Pass - Payment methods - final screen

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#23]
AA

![2ndpass-30th-april-paymnet methods](https://cloud.githubusercontent.com/assets/7224727/7405032/aaa55708-ef2f-11e4-9045-0ed459c18a4f.png)

**Comment by galenp** [comment]
Possible/Probable dupe of  galenp/PROPERTYCOMPASS.ISSUES#14
Which was resolved  in c7f70e116f2f07cd548684589446888042953e17

Going to close for now.
