### ISSUE TITLE
PC 1 - confirm property details

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#33]
see attached

AA

![2 0iprlaunch-pc1-confirm-property-details](https://cloud.githubusercontent.com/assets/7224727/7451611/fd5a0c14-f295-11e4-817a-b86168f2ecf3.png)

**Comment by galenp** [comment]
That screenshot was already outdated before the ticket was raised.

I've addressed most of the issues from this ticket and moving it to the Resolved state.
