### ISSUE TITLE
PC 2 - complete

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#39]
![2 0iprlaunch-pc2-5-complete](https://cloud.githubusercontent.com/assets/7224727/7452753/0830a2ce-f2a5-11e4-8ad0-6e756c0301ab.png)

**Comment by galenp** [comment]
I'm not sure about changing the public-facing Id ... the Order Id is what the user has been mostly exposed to during the pending->provisioning process. That I think should be continued through to the 'tax invoice' process.

I do agree with showing the receipt number.

**Comment by anthonyaoun** [comment]
in Confidis we have this system

1) T-ipr<number>
2) R-ipr<number>

we could have 

1) O-ipr-12345678
2) R-ipr-12345678

note the number is the same. the pretext

O = order
R = receipt
number is the same for the same property address/ order

Hence the pre-text can assist

We could include in the pre-text a code for the review/ report type

AA

**Comment by galenp** [comment]
![image](https://cloud.githubusercontent.com/assets/1113659/7471839/625dc844-f35e-11e4-9bed-19e33dbe1e87.png)

**Comment by galenp** [comment]
Order # is the same # as the Invoice #
An invoice is a fulfilled order that also has a receipt #
