### ISSUE TITLE
Property details - collect data screen

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#4]
Please see attached

Thank you

AA

![propertydetails-collect](https://cloud.githubusercontent.com/assets/7224727/7384836/c54abfc4-ee7d-11e4-9923-b6c451818ffd.png)

**Comment by galenp** [comment]
I want to see consistent labelling... why then are we mixing Reviews + Reports?

**Comment by galenp** [comment]
Rental Review
Historical Growth Review
Property Review

**Comment by galenp** [comment]
Do we need to specify the acronym IPR everywhere? Or even at all? Does this offer anything or just confuse the user.
