### ISSUE TITLE
PC 2 - email

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#41]
![2 0iprlaunch-pc2-7-ipr-email](https://cloud.githubusercontent.com/assets/7224727/7452771/42840cf4-f2a5-11e4-8866-b25a511c1561.png)

**Comment by galenp** [comment]
![image](https://cloud.githubusercontent.com/assets/1113659/7453898/89409298-f2a0-11e4-8bc7-7815702b6f45.png)

I just published a review and this is the email i got which is in the expected format.

I am very confused by this... there shouldnt be anything that changes the e-mails from me to you.

Investigating

**Comment by galenp** [comment]
I have confirmed the BCC of your e-mail was also formatted badly in my inbox.

Investigations continuing...

**Comment by galenp** [comment]
can you please test this again anthony

**Comment by galenp** [comment]
![image](https://cloud.githubusercontent.com/assets/1113659/7488956/8c634ba0-f403-11e4-95f1-79a5aff5d69e.png)

**Comment by galenp** [comment]
Broken e-mails don't come from SendGrid!
