### ISSUE TITLE
PC 1 - Propdata

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#43]
![2 0iprlaunch-pc2-propdata-1](https://cloud.githubusercontent.com/assets/7224727/7452808/a86bc41c-f2a5-11e4-818c-91f6c9991881.png)
![Uploading 2.0iprLaunch-PC2-propdata-2.png…]()

**Comment by galenp** [comment]
addressed in propdata commit 133cc4683e10c5aafa5797c77aeeba4c1567c76f
