### ISSUE TITLE
Account helper

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#49]
please see attached

AA

![fp-1-accounthelper](https://cloud.githubusercontent.com/assets/7224727/7488993/dfc7a30c-f414-11e4-897e-935da588f279.png)

**Comment by galenp** [comment]
Addressed:
You can test by navigating too
https://bridge.propertycompass.com.au/migration/index/750b9c9f-0735-4460-9c1f-cd88e4873322

BUT DONT CLICK CONTINUE

**Comment by anthonyaoun** [comment]
Thank you
