### ISSUE TITLE
Order ipr form PC1

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#51]
![fp-3-orderipr](https://cloud.githubusercontent.com/assets/7224727/7489001/1b009096-f415-11e4-9d88-a539654ecda1.png)

**Comment by galenp** [comment]
Ok the bridging application and PC2 are using 2 completely separate themes/layouts/color pallets.

I don't see a need that the exact colors must match because we are not trying to pass these off as the same system.

I'll action the other changes but will skip color matching.

**Comment by galenp** [comment]
Ok to test

**Comment by anthonyaoun** [comment]
Thank you
