### ISSUE TITLE
Account success

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#52]
![fp-4-success](https://cloud.githubusercontent.com/assets/7224727/7489010/3e959fba-f415-11e4-8dfb-3681d13452c7.png)

**Comment by galenp** [comment]
Resolved can test at:

https://bridge.propertycompass.com.au/ipr/success/89e7a7c2-858b-429b-98be-199e3659ec6f

**Comment by anthonyaoun** [comment]
Thank you
