### ISSUE TITLE
Property details

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#53]
![fp-5-propertydetails](https://cloud.githubusercontent.com/assets/7224727/7489025/823598c4-f415-11e4-8dde-b3dac8688386.png)

**Comment by galenp** [comment]
Resolved in commit b4e0a7f23dfae0ab1e8d587098214e21404e94bb

**Comment by galenp** [comment]
galenp/PROPERTYCOMPASS.APP@b4e0a7f23dfae0ab1e8d587098214e21404e94bb

**Comment by anthonyaoun** [comment]
Thank you
