### ISSUE TITLE
Edit profile

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#61]
Does not work

AA

**Comment by galenp** [comment]
More details... what doesn't work?

**Comment by galenp** [comment]
Are you are PC account?
External account?
What fields are you trying to update?

**Comment by anthonyaoun** [comment]
Both type of logins and I can not edit any field

**Comment by galenp** [comment]
Please provide screen-shot... I  just tested and I was able to:
1. edit my company
2. click save
3. notice the 'blue profile has changed popup'
4. leave screen
5. come back to profile
6. company is there.

**Comment by anthonyaoun** [comment]
![edit-profile](https://cloud.githubusercontent.com/assets/7224727/8177496/b5f043d2-1448-11e5-9ea4-4faad0f3dea2.png)

**Comment by galenp** [comment]
how are you navigating to that address?

Are you clicking the arrow next to your name and then clicking profile?

**Comment by anthonyaoun** [comment]
1) Dashboard

2) Profile / edit

AA
