### ISSUE TITLE
testing - Report [creating the pdf]

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#65]
Please see attached, this happens in Report and not in Map / PDF

some of the data is captured and put into the PDF.

I then have to refresh the screen to get the full PDF

Thank you

![feedback1](https://cloud.githubusercontent.com/assets/7224727/8198659/32e211c8-14ed-11e5-8728-7c64cbf706e6.png)
![feedback0](https://cloud.githubusercontent.com/assets/7224727/8198658/32e0d880-14ed-11e5-9a65-d75636fed138.png)

**Comment by galenp** [comment]
see if this still occurs since the hotfix

**Comment by galenp** [comment]
please check this so we can close this issue if its fixed

**Comment by galenp** [comment]
Just made a change to the report data retrieval process and I'm pretty sure it's fixed now.
