### ISSUE TITLE
Preview content

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#70]
The following are missing from the preview page

![pc-01](https://cloud.githubusercontent.com/assets/7224727/11450504/55632ae0-95f6-11e5-8d45-706f6baf8ca6.png)

**Comment by galenp** [comment]
![image](https://cloud.githubusercontent.com/assets/1113659/11466862/4789e96a-977f-11e5-9d30-a97cc045eba0.png)
