### ISSUE TITLE
Fields being saved then unticked. 

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#71]
Please see attached

AA

![pc-02](https://cloud.githubusercontent.com/assets/7224727/11450512/ca6ddc68-95f6-11e5-80c5-eb4bc59de352.png)

**Comment by galenp** [comment]
As per this list these 3 fields are not Residential Real Estate features, perhaps I used UI list from MyDesktop. 

For the time being I'll remove from the front end.

http://reaxml.realestate.com.au/docs/reaxml1-xml-format.html#features

**Comment by anthonyaoun** [comment]
Found another field: First Home Buyers

saves then un-ticks

AA

**Comment by galenp** [comment]
Fixed.

**Comment by anthonyaoun** [comment]
Thank you
