### ISSUE TITLE
Property type | read-only, after property is saved

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#74]
Please see attached

![pc-05](https://cloud.githubusercontent.com/assets/7224727/11450615/77f8d1f0-95fa-11e5-9004-3f98e12e0e19.png)

**Comment by galenp** [comment]
Just a bug.

Residential Category (what you are referring too in the screen shots) is changeable after a listing has been created.

For Land listings there is no Category as this is just 'Residential'

For Rural listings there is a different selection of categories which specify the type of farm.

**Comment by galenp** [comment]
This bug is resolved in PC.Property#1.0.3 component which has now made it's way onto the staging environment.

https://bitbucket.org/propertycompass/pc.component.property/commits/450f950983a31a45a8499aaf43d0ed7cbc740c29

**Comment by anthonyaoun** [comment]
Thank you
