### ISSUE TITLE
Managing images

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#77]
![pc-08](https://cloud.githubusercontent.com/assets/7224727/11450683/fbd65df6-95fc-11e5-984d-bf54aa693ff9.png)

**Comment by galenp** [comment]
Resolved in galenp/PROPERTYCOMPASS.APP@609b292bce3a7c3258f81ce4f1e16a3b78c252f6

**Comment by anthonyaoun** [comment]
perfect! thank you
