### ISSUE TITLE
Loading files - incorrect selection of section may cause significant frustrations 

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#80]
Please see attached and call me for explanation

AA

![loading](https://cloud.githubusercontent.com/assets/7224727/11734942/c49b57de-a00f-11e5-8e8e-5d46452a34de.png)

**Comment by galenp** [comment]
So the Browser treated the "drop" as a Browser.Open action in the Tab you are viewing. This is standard browser behaviour and can't be changed. It wouldn't matter the specific location on the page you did this the result would be the same in all areas that are not the specific File Drop Zone.

With regards to confusion on blank rectangles that look like drop zones... i think there is a case for this. I'll tweak the UI to reduce that empty space when there are no files already loaded.

**Comment by anthonyaoun** [comment]
The frustration comes from losing all my data. The property has not been saved as a draft yet. I have to do it all again. simple but frustrating

AA

**Comment by anthonyaoun** [comment]
Please see attached suggestion

![loadingfiles](https://cloud.githubusercontent.com/assets/7224727/11737051/2dfec22e-a029-11e5-99f5-297580b271bd.png)
