### ISSUE TITLE
Managing Contacts 

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#83]
Tried to add a contact AFTER i deleted a contact does not work

See attached

![contact-management](https://cloud.githubusercontent.com/assets/7224727/11735230/0ebedd42-a013-11e5-9205-931ac4d7b9de.png)

**Comment by galenp** [comment]
Resolved in galenp/PROPERTYCOMPASS.APP@21351ba2b152fe8168d071ea60a5030bda6f0b2e
