### ISSUE TITLE
Loading images via a URL

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#84]
Please see attached

![loading-images](https://cloud.githubusercontent.com/assets/7224727/11735292/ac389f18-a013-11e5-8515-355c6608f3e3.png)

**Comment by galenp** [comment]
Using URLs for attachment locations should work as its a standard browser/operating system feature and nothing specific to the code.

As a side note..we walked through the bulk image migration process..
1) Goto source site, LEFT MOUSE BUTTON on image and click Save Image
2) Repeat above for however many images there are
3) Click Upload Image Drop Area
4) Highlight all images saved
5) Click upload

**Comment by anthonyaoun** [comment]
I recall this process. I did it anyway

The point is, it worked for doc. BUt not for images. Can you explain why? 

AA

**Comment by galenp** [comment]
Not sure, Just tested and it worked for me.

Try again... maybe its got something to do with the location the image comes from.

But my test has it working as expected so im going to close this.

**Comment by anthonyaoun** [comment]
Yes it could our location; this server could be down

It could be affecting PC1. I can load images there

AA
