### ISSUE TITLE
Import and Publish functionality

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#85]
Galen

this is a suggestion for cases where the entire imported file can be published/ select a publish to site

See attached

AA

![pc-import](https://cloud.githubusercontent.com/assets/7224727/11858961/67c28dc0-a4ba-11e5-951f-2718cfec9855.png)

**Comment by galenp** [comment]
This enhancement was completed galenp/PROPERTYCOMPASS.APP@9efa7a2ac7bbf5d99c30c3b257576cfb960bbb08
