### ISSUE TITLE
Document names

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#86]
Hello Galen

Please fix documents names/ urls as per dicussions. See image attached

Thank you
AA

![29thfeedback-part2](https://cloud.githubusercontent.com/assets/7224727/13038421/e0159ac8-d3e6-11e5-96dd-a3bee493a0b0.png)

**Comment by galenp** [comment]
Resolved in galenp/PROPERTYCOMPASS.APP@ab6eeb0dea501842b6852e67c15d2ca29c78116e
