### ISSUE TITLE
PC2

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#87]
This user had added several images to his property, the first 2 are 0.k whilst the others are copies of image number3 

trevor@apsdevelopments.com.au

This is his property

http://www.centralpropertyexchange.com.au/#!/details/ff2d569c-7863-4352-8829-47bd17023714

Thank you
AA

**Comment by galenp** [comment]
Resolved in web app build 0.5.3

**Comment by galenp** [comment]
Resolved in galenp/PROPERTYCOMPASS.APP@aab2f4915a237a6be225c0ab3619b9b47778469f
