### ISSUE TITLE
Viewable fields

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#91]
I think these should match the pdf IN VIEW LIST MODE

![viewable fields](https://cloud.githubusercontent.com/assets/7224727/14412772/6fa23c68-ffad-11e5-931c-c6a2c196bf6b.png)

**Comment by galenp** [comment]
There is a compelling case to have a variety of Price List templates for different user stories. However I think that should be raised when its required in a new issue as a feature request. Going to close this one for now since its not on the immediate radar.
