### ISSUE TITLE
Connect

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#92]
Hi Galen

please see attached

![connect](https://cloud.githubusercontent.com/assets/7224727/14423394/fbd611a2-001e-11e6-99a1-0442ee1ee292.png)

**Comment by galenp** [comment]
normal

only takes long because its development environment

It doesnt know that you are or are not an existing user. So it stores your invitation code.

Once you log in it triggers the PopUp

**Comment by galenp** [comment]
I don't think there is an issue here asides from the slow load time which i believe is only a DEV environment issue.

**Comment by galenp** [comment]
Please retest, keeping in mind the workflow covers the following scenarios;

1) Existing user receiving an invitation that is NOT logged in
2) Existing user receiving an invitation that IS already logged in
3) New User receiving an invitation that does not have an account and will manually create an account
4) New User receiving an invitation that will 'Sign In' with a social account

1 workflow, all use cases

**Comment by galenp** [comment]
Significant improvements to the invitation, login flow has been made since this issue was raised, closing.
