### ISSUE TITLE
List name change

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#93]
please see attached

AA

![listnamechange](https://cloud.githubusercontent.com/assets/7224727/14423669/548d04e4-0020-11e6-93f1-4aacd31b906b.png)

**Comment by galenp** [comment]
While i acknowledge your layout suggestions they don't justify the architecture changes required to fulfil them.

Going to close this, as the layout used is not really up for structural modification. Will discuss more with you over skype.
